### ISSUE TITLE
[Feature] Change python scripts.

### ISSUE THREAD

**Issue by p-groarke** [axlib/AudioTools#10]
Doesn't seem to be possible.

Idea: Add a script field to the panels inspector (file opener). In the futur, that would allow multiple scripts per instruments (possible?).

**Comment by ghost** [comment]
Multiple scripts per instrument could be possible but it would be hard to for the user to manage the global variables when loading a script from somebody else.

Refer to issue #1 .

**Comment by p-groarke** [comment]
But can we change script? I can only use simple_saw.py right now...

**Comment by ghost** [comment]
Nope for now that’s the only file. That’s my next todo.

**Comment by ghost** [comment]
Im doing it tomorrow.
