### ISSUE TITLE
Trying to change color (click).

### ISSUE THREAD

**Issue by p-groarke** [axlib/AudioTools#12]
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000003c
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x3c:
--> 
    __TEXT                 000000010413b000-00000001043e3000 [ 2720K] r-x/rwx SM=COW  /Applications/AudioTools.app/Contents/MacOS/AudioTools

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ax.AudioTools                   0x0000000104148859 ax::Window::Event::Function<char>::operator()(char) + 57
1   ax.AudioTools                   0x0000000104147a1b axKeyboardManager::GrabKey(ax::Window_) + 91
2   ax.AudioTools                   0x00000001041d10ac ax::Window::Event::GrabKey() + 44
3   ax.AudioTools                   0x00000001041b2bac ax::TextBox::OnMouseLeftDown(ax::Utils::Point2D<int> const&) + 188
4   ax.AudioTools                   0x00000001041b8ab9 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (ax::TextBox::_&)(ax::Utils::Point2D<int> const&), ax::TextBox_, std::__1::placeholders::__ph<1>&>&, ax::Utils::Point2D<int> >(std::__1::__bind<void (ax::TextBox::_&)(ax::Utils::Point2D<int> const&), ax::TextBox_, std::__1::placeholders::__ph<1>&>&&&, ax::Utils::Point2D<int>&&) + 585
5   ax.AudioTools                   0x00000001041b879c std::__1::__function::__func<std::__1::__bind<void (ax::TextBox::_&)(ax::Utils::Point2D<int> const&), ax::TextBox_, std::__1::placeholders::__ph<1>&>, std::__1::allocator<std::__1::__bind<void (ax::TextBox::_&)(ax::Utils::Point2D<int> const&), ax::TextBox*, std::__1::placeholders::__ph<1>&> >, void (ax::Utils::Point2D<int>)>::operator()(ax::Utils::Point2D<int>&&) + 60
6   ax.AudioTools                   0x0000000104181202 std::__1::function<void (ax::Utils::Point2D<int>)>::operator()(ax::Utils::Point2D<int>) const + 162
7   ax.AudioTools                   0x00000001041d466d ax::Window::Event::Functionax::Utils::Point2D<int >::operator()(ax::Utils::Point2D<int>) + 93
8   ax.AudioTools                   0x00000001042ecc72 axMouseManager::OnMouseLeftDown(ax::Utils::Point2D<int> const&) + 1234
9   ax.AudioTools                   0x0000000104158851 -[axAppDelegate mouseDown:] + 641
10  com.apple.AppKit                0x00007fff92befd1d -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
11  com.apple.AppKit                0x00007fff92bf0fad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
12  com.apple.AppKit                0x00007fff92549735 -[NSWindow sendEvent:] + 517
13  com.apple.AppKit                0x00007fff92545e49 -[NSApplication sendEvent:] + 2540
14  com.apple.AppKit                0x00007fff9247903a -[NSApplication run] + 796
15  ax.AudioTools                   0x00000001041adfbc axCallNSApplicationMain() + 124
16  ax.AudioTools                   0x00000001042ae091 axCoreMac::MainLoop() + 17
17  ax.AudioTools                   0x000000010429e899 ax::Core::Facade::MainLoop() + 25
18  ax.AudioTools                   0x000000010428a9e2 ax::editor::App::MainLoop() + 1266
19  ax.AudioTools                   0x000000010418fdc1 main + 33
20  libdyld.dylib                   0x00007fff8f4ff5ad start + 1

**Comment by ghost** [comment]
Fix in e66f8d8a0545b63e0923bff6c3b0c08f6e377c57, needed to remove handle window from inspector menu when deleting widget.
