### ISSUE TITLE
[Bug] setMul causes sound to repeat infinitely.

### ISSUE THREAD

**Issue by p-groarke** [axlib/AudioTools#16]
This is the issue we where hearing (notes never stop). It is setMul.

To reproduce:
- create a simple Sine or whatever that plays and you can hear without modifying volume.
- define a method that uses setMul.
- When changing volume, sound starts repeating non-stop.

**Comment by p-groarke** [comment]
Example:

midi = Notein(scale=1);
midi_env = MidiAdsr(midi['velocity'], attack=0.05, decay=0.1, sustain=0.4, release=0.1);

saw_wave = SuperSaw(freq=midi['pitch'], detune=0.5, bal=0.7, mul=midi_env).out();

def OnVolume(v):
    saw_wave.setMul(v);

def OnMix(v):
    saw_wave.setBal(v);

def OnDetune(v):
    saw_wave.setDetune(v);

**Comment by ghost** [comment]
Seem to be fix by doing this

```
midi = Notein(scale=1);
midi_env = MidiAdsr(midi['velocity'], attack=0.05, decay=0.1, sustain=0.4, release=0.1);
pitch = midi['pitch'];

saw_wave = SuperSaw(freq=pitch, mul=midi_env);
saw_pan = Pan(saw_wave, outs=2);
output = Mix(saw_pan, voices=2).out();

def SetVolume(value):
    output.setMul(value);
```
